db:
  scale: 1
web:
  scale: 1
  health_check:
    port: 3000
    interval: 60000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: none
    response_timeout: 2000
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 5
